version: "3"

services:
  backend:
    image: python:3.10
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python backend.py

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
